name: AmbientWeather2MQTT
version: "1.0.0"
slug: hassio_aw2m
description: This package listens for local data from Ambient Weather stations (such as the WS-2902C) and converts the incoming data to MQTT events.
startup: application
boot: auto
ports:
  8132/tcp: 8132
# TODO need to make the options respected as env variables
options:
  STATION_MAC_ADDRESS: ""
  MQTT_SERVER: ""
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  TZ: "America/Chicago"
schema:
  STATION_MAC_ADDRESS: "str"
  MQTT_SERVER: "str"
  MQTT_USERNAME: "str"
  MQTT_PASSWORD: "str"
  TZ: "str"
environment:
  PORT: "8132"
services:
  - "mqtt:need"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
